import type { Metadata } from "next";
import Link from "next/link";
import "../legal.css";

export const metadata: Metadata = {
  title: "Terms of Service | Neuvra AI",
  description: "Terms of Service for Neuvra AI",
};

export default function TermsPage() {
  return (
    <div className="legal-page">
      <div className="legal-wrap">
        <Link href="/" className="legal-back">← Back to Neuvra</Link>

        <h1>Terms of Service</h1>
        <p className="legal-date">Last updated: May 12, 2025</p>

        <p>
          Welcome to Neuvra AI. By accessing or using our platform at{" "}
          <strong>neuvraai.com</strong>, you agree to be bound by these Terms of
          Service. Please read them carefully.
        </p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By creating an account or using Neuvra AI, you confirm that you are at
          least 13 years old and agree to these Terms. If you are using Neuvra on
          behalf of an organization, you represent that you have authority to bind
          that organization to these Terms.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          Neuvra AI is an AI-powered study and research platform that provides
          tools including an AI tutor, flashcard generation, research assistance,
          PDF analysis, smart notes, and a memory engine. The service is provided
          on a subscription basis with Free and Pro plans.
        </p>

        <h2>3. Account Registration</h2>
        <p>
          You must provide accurate and complete information when creating your
          account. You are responsible for maintaining the security of your
          credentials and for all activity under your account. Notify us
          immediately at{" "}
          <a href="mailto:hello@neuvra.ai">hello@neuvra.ai</a> if you suspect
          unauthorized access.
        </p>

        <h2>4. Subscriptions and Payments</h2>
        <p>
          Neuvra AI offers a free tier and paid Pro subscription. Paid
          subscriptions are billed in advance on a monthly or yearly basis.
          Payments are processed securely by Paddle, our Merchant of Record.
          Paddle handles all tax collection and compliance on your behalf.
        </p>
        <p>
          Your subscription automatically renews unless canceled before the end
          of the current billing period. You can cancel at any time from your
          account settings.
        </p>

        <h2>5. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the service for any unlawful purpose</li>
          <li>Attempt to reverse-engineer or extract our AI models</li>
          <li>Share your account credentials with others</li>
          <li>Use automated tools to scrape or abuse the platform</li>
          <li>Upload content that infringes third-party intellectual property</li>
        </ul>

        <h2>6. AI-Generated Content</h2>
        <p>
          Content generated by Neuvra AI (summaries, flashcards, explanations)
          is provided for educational purposes. We do not guarantee accuracy.
          You are responsible for verifying AI-generated content before relying
          on it for academic or professional purposes.
        </p>

        <h2>7. Intellectual Property</h2>
        <p>
          Neuvra AI and its original content, features, and functionality are
          owned by Neuvra and protected by applicable intellectual property laws.
          Content you upload remains yours — we only process it to provide the
          service.
        </p>

        <h2>8. Privacy</h2>
        <p>
          Your use of Neuvra is also governed by our{" "}
          <Link href="/privacy">Privacy Policy</Link>, which is incorporated into
          these Terms by reference.
        </p>

        <h2>9. Termination</h2>
        <p>
          We reserve the right to suspend or terminate accounts that violate
          these Terms. You may delete your account at any time. Upon termination,
          your right to use the service ceases immediately.
        </p>

        <h2>10. Disclaimer of Warranties</h2>
        <p>
          The service is provided "as is" without warranties of any kind. We do
          not guarantee uninterrupted or error-free operation. To the fullest
          extent permitted by law, Neuvra disclaims all implied warranties.
        </p>

        <h2>11. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, Neuvra shall not be liable for
          any indirect, incidental, or consequential damages arising from your
          use of the service. Our total liability shall not exceed the amount you
          paid us in the 12 months preceding the claim.
        </p>

        <h2>12. Changes to Terms</h2>
        <p>
          We may update these Terms from time to time. We will notify you of
          significant changes via email or in-app notification. Continued use of
          the service after changes constitutes acceptance of the new Terms.
        </p>

        <h2>13. Contact</h2>
        <p>
          For questions about these Terms, contact us at{" "}
          <a href="mailto:hello@neuvra.ai">hello@neuvra.ai</a>.
        </p>
      </div>
    </div>
  );
}
